import { ArrowRight, Check, GitBranch, Sparkles } from "lucide-react";
import { motion } from "motion/react";
import { Link } from "react-router-dom";

const details = ["Import your accessible GitHub repositories", "Index code context when you choose", "Review pull requests in one workspace"];

export default function AuthPage() {
  return <main className="min-h-screen overflow-hidden bg-[#10120e] text-stone-100 lg:grid lg:grid-cols-[1fr_1.05fr]">
    <section className="dark-grid relative hidden overflow-hidden border-r border-white/10 p-10 lg:flex lg:flex-col"><motion.div initial={{ opacity: 0, scale: .9 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .6 }} className="absolute -right-24 top-1/2 size-96 -translate-y-1/2 rounded-full border border-[#b8f250]/20 bg-[#b8f250]/5 shadow-[0_0_140px_rgba(184,242,80,.11)]" /><Link to="/" className="relative flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#b8f250] text-[#11130f]"><Sparkles className="size-4" /></span><span className="font-semibold tracking-[-.03em] text-white">ReviewFlow</span></Link><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .15, duration: .55 }} className="relative my-auto max-w-lg"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#b8f250]">Your GitHub review room</p><h1 className="mt-5 text-5xl font-semibold leading-[.98] tracking-[-.06em] text-white">Every pull request deserves its full context.</h1><p className="mt-6 max-w-md text-base leading-7 text-stone-400">ReviewFlow uses your GitHub access to create a focused, repository-aware review workspace.</p><ul className="mt-10 space-y-4 text-sm text-stone-300">{details.map((item, index) => <motion.li initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: .3 + index * .1 }} key={item} className="flex items-center gap-3"><span className="grid size-5 place-items-center rounded-full bg-[#b8f250]/15"><Check className="size-3 text-[#b8f250]" /></span>{item}</motion.li>)}</ul></motion.div><p className="relative text-xs text-stone-600">ReviewFlow · GitHub-powered code reviews</p></section>
    <section className="quiet-grid flex min-h-screen items-center justify-center bg-[#f8f8f5] px-5 py-12 text-slate-950"><motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .5 }} className="w-full max-w-md"><Link to="/" className="mb-12 flex items-center gap-3 lg:hidden"><span className="grid size-9 place-items-center rounded-xl bg-[#b8f250] text-[#11130f]"><Sparkles className="size-4" /></span><span className="font-semibold tracking-[-.03em]">ReviewFlow</span></Link><p className="eyebrow">GitHub sign in</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.05em]">Open your review workspace.</h2><p className="mt-3 max-w-sm text-sm leading-6 text-stone-500">Continue with GitHub to load the repositories and pull requests your account can access.</p><motion.a whileHover={{ y: -2 }} whileTap={{ scale: .985 }} href="/api/auth/github" className="mt-8 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#171914] text-sm font-semibold text-white shadow-lg shadow-[#171914]/15 transition hover:bg-[#292d25]"><GitBranch className="size-4" /> Continue with GitHub <ArrowRight className="ml-1 size-4" /></motion.a><p className="mt-10 text-center text-sm text-stone-500">New here? Your ReviewFlow workspace is created automatically when you continue with GitHub.</p></motion.div></section>
  </main>;
}
